# Generated by Django 4.1.5 on 2023-03-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_interviewanswer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewanswer',
            old_name='question',
            new_name='questions',
        ),
    ]
