# Generated by Django 4.1.5 on 2023-03-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_rename_question_interviewanswer_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewanswer',
            old_name='questions',
            new_name='question',
        ),
    ]
